### ISSUE TITLE
Error: E2EE Key has not been saved, try register `saveE2EESelfKeyDataByKeyId` or use E2EE Login

### ISSUE THREAD

**Issue by Suphachock** [evex-dev/linejs#41]
I got and error when my line API send or reply message

**Comment by EdamAme-x** [comment]
wait a minute

**Comment by EdamAme-x** [comment]
Do you use `FileStorage`? If not understand, please see [https://linejs.evex.land](https://linejs.evex.land)

**Comment by Suphachock** [comment]
Now it error Request internal failed: {"code":"NOT_FOUND","reason":"there is no valid group key"}
when call message.send()

**Comment by EdamAme-x** [comment]
Once you send a message in the group you want to send it to, try it out;  
LINE does not generate shared keys by first.

**Comment by Suphachock** [comment]
Can u example code for send message to group?

**Comment by Suphachock** [comment]
Mean I can't send message to specify group by group id?

**Comment by EdamAme-x** [comment]
Possible. If you cannot follow this procedure, there may be a bug.

**Comment by Suphachock** [comment]
message.send({
 to: "XXXXXXXXXXXXXXXXXX",
 text: "Hello, this is a message!",
});
In first version I use this code for send message by specify group and it work  but now in the last version why it cannot work?

**Comment by piloking** [comment]
linejs does not currently support generating encryption keys for groups.
You will first need to generate a key by sending a message to the group in your app.

**Comment by piloking** [comment]
And to send a message to a specific chat:
```js
client.on("ready", (user) => {
  console.log(`Logged in as ${user.displayName} (${user.mid})`);
  client.sendMessage({to:"mid",text:"text!"})
});
```
