### ISSUE TITLE
How to get previous messages from square chat

### ISSUE THREAD

**Issue by KazumiLine** [evex-dev/linejs#42]
Hello 
how can i get previous messages by updating the sync token for FetchSquareChatEvents

i tried decode the sync token with TBinaryProtocol and got,

struct {
1: A?? int64,
2: B?? int64,
3: C?? int64
4: D?? int64
5: E?? int64
6: F?? int64
7: G?? int64
8: H?? struct {
	1: X?? int32
}
9: I?? struct {
	1: Y?? map[string]int64
}
10: J?? int64
}

**Comment by EdamAme-x** [comment]
You can learn more about it here
discord.gg/evex

**Comment by KazumiLine** [comment]
fixed
