### ISSUE TITLE
bug: ~INTERNAL_ERROR: Failed to issue V3 token

### ISSUE THREAD

**Issue by QA-ZongweiLu** [evex-dev/linejs#46]
## What happened?

When I was testing email login using v3, I got this error.

### Error message or Bug description

```json
{
  "type": "Request internal failed",
  "data": {
      "code": "INTERNAL_ERROR",
      "reason": "Failed to issue V3 token"
    }
}
```

## Environment
Device: Ipad Air 4
OS: iPadOS 18.0
Line App Version: 14.17.1

**Comment by EdamAme-x** [comment]
I'll check

**Comment by EdamAme-x** [comment]
IOSIPAD doesn't support v3 token, so please use other device.

```
.login({
  ...,
  device: "..."
})
```

**Comment by QA-ZongweiLu** [comment]
@EdamAme-x 
It works. Thanks for your help

**Comment by EdamAme-x** [comment]
sure
and thanks @piloking
